// Package radar implements RADAR (Risk Aware Diff Auto Review), the layered
// code-review automation funnel described in "Automating Low-Risk Code Review
// at Meta: RADAR, Risk Calibration, and Review Efficiency" (arXiv:2605.30208).
//
// RADAR classifies every code-review diff and decides whether it can be
// auto-approved / auto-landed without human review (when it is genuinely
// low-risk) or must be routed to a human reviewer. The funnel combines
// authorship classification, eligibility gates, a Diff Risk Score (DRS), an
// Automated Code Review (ACR) agent, and deterministic validation.
//
// The entry point is Engine.Classify, which routes a Diff through the funnel
// and returns a DecisionTrace recording the final Decision and every stage that
// was evaluated.
package radar

import "time"

// SourceType identifies who authored a diff and, for bots, which automation
// produced it. Authorship classification (paper §2.7.1) is the first branch in
// the funnel: human-authored diffs and bot-authored diffs follow different
// pipelines, and bot diffs are further split by automation source because each
// source has a distinct risk profile and eligibility model (Table 1).
type SourceType int

const (
	// SourceHuman is a diff written by a human engineer. It enters the RADAR
	// Verification + Approval pipeline (paper §2.9).
	SourceHuman SourceType = iota
	// SourceDeterministicCodemod is a fully-specified, non-LLM transformation
	// from CodemodService (e.g. API migrations, import reorganization). When the
	// codemod itself has been vetted, its diffs are Blanket AutoAccepted and skip
	// per-diff review entirely (paper §2.7.2).
	SourceDeterministicCodemod
	// SourceAICodemod is an LLM-generated CodemodService change. Because each diff
	// may vary with model output, it cannot be blanket-approved and must pass the
	// ACE pipeline per-diff (Conditional AutoAccept, paper §2.7.2).
	SourceAICodemod
	// SourceRACERRunbook is a diff generated by a RACER runbook (Meta's GenAI bulk
	// code-change tool). It is the most granular eligibility path: each runbook is
	// evaluated independently before its diffs enter the ACE pipeline (paper §2.7.2).
	SourceRACERRunbook
)

// String returns the human-readable name of the source type.
func (s SourceType) String() string {
	switch s {
	case SourceHuman:
		return "human"
	case SourceDeterministicCodemod:
		return "deterministic-codemod"
	case SourceAICodemod:
		return "ai-codemod"
	case SourceRACERRunbook:
		return "racer-runbook"
	default:
		return "unknown"
	}
}

// IsBot reports whether the source is bot-authored (any non-human source).
func (s SourceType) IsBot() bool { return s != SourceHuman }

// CISignal is the state of continuous-integration signals for a diff. RADAR
// requires CI to be in an allowed (passing) state before a diff is eligible for
// automated review (paper §2.7.3, §2.9).
type CISignal int

const (
	// CIUnknown means CI has not reported yet; treated as not-allowed.
	CIUnknown CISignal = iota
	// CIPassing means all required CI signals are green.
	CIPassing
	// CIFailing means at least one required CI signal failed.
	CIFailing
)

// DiffState is the lifecycle state of a diff. Only diffs in an allowed state
// (the latest published version, not work-in-progress / request-for-comment /
// previously rejected) are eligible (paper §2.9).
type DiffState int

const (
	// DiffPublished is the latest published, review-ready version of a diff.
	DiffPublished DiffState = iota
	// DiffWorkInProgress is a draft / WIP diff, not yet ready for review.
	DiffWorkInProgress
	// DiffRequestForComment is a diff published only to gather comments (RFC).
	DiffRequestForComment
	// DiffRejected is a diff a reviewer has already rejected.
	DiffRejected
)

// ChangeSignal is a semantic tag attached to an individual change in a diff,
// describing what the change does. The ACR agent (paper §2.4) classifies a diff
// by the signals present across its changes: a diff is safe to auto-land only
// when it carries safe signals and zero risk signals. See acr.go for the safe
// and risk signal taxonomies (SafeSignals / RiskSignals).
type ChangeSignal string

// Change is a single semantic unit of a diff (e.g. one hunk or one logical
// edit), annotated with the signals the ACR agent uses to reason about risk.
// In a real deployment these signals would be inferred by the LLM reviewer or
// static analysis; here they are carried on the structured input so the
// rule-based ACR can operate deterministically and the LLM ACR can be fed the
// raw Content.
type Change struct {
	// File is the repository path the change touches.
	File string `json:"file"`
	// Content is the raw text of the change (used by the LLM ACR adapter).
	Content string `json:"content,omitempty"`
	// Signals are the semantic tags for this change (safe and/or risk signals).
	Signals []ChangeSignal `json:"signals,omitempty"`
	// Complexity is the change's review-effort / complexity score. A score of 4
	// or above is itself a risk signal (paper §2.4).
	Complexity int `json:"complexity,omitempty"`
}

// Author describes the engineer or bot account that authored a diff and the
// attributes RADAR uses for human author-eligibility checks (paper §2.7.3).
type Author struct {
	// Name identifies the author (engineer handle or bot account).
	Name string `json:"name"`
	// EligibleRole is true when the author holds an eligible SWE job family role
	// (including management, Data Engineers, Data Scientists).
	EligibleRole bool `json:"eligible_role"`
	// HasOncallOwnership is true when the author has an associated operational
	// oncall ownership for the changed code.
	HasOncallOwnership bool `json:"has_oncall_ownership"`
	// TenureDays is the author's employment tenure in days. SWE interns require at
	// least 60 days (see InternMinTenureDays).
	TenureDays int `json:"tenure_days"`
	// IsIntern marks SWE interns, who are subject to the minimum-tenure check.
	IsIntern bool `json:"is_intern"`
	// DiffsLastYear is the number of diffs the author has landed in the past year.
	// Authors with 10 or fewer are excluded from automated review.
	DiffsLastYear int `json:"diffs_last_year"`
}

// Diff is the unit RADAR classifies: one code change with the metadata and
// structured content the funnel needs to route it. It mirrors a Phabricator
// diff together with the derived signals used by the pipeline.
type Diff struct {
	// ID is the diff identifier (for tracing and reporting).
	ID string `json:"id"`
	// Org is the organization that owns the diff; its OrgPolicyConfig governs
	// thresholds and which automation sources are permitted (paper §2.7.4).
	Org string `json:"org"`
	// Source is the authorship / automation source type.
	Source SourceType `json:"source"`
	// Author carries the human author-eligibility attributes (human diffs only).
	Author Author `json:"author"`
	// Runbook is the RACER runbook name (SourceRACERRunbook only); it selects the
	// per-runbook eligibility config from the RunbookRegistry.
	Runbook string `json:"runbook,omitempty"`
	// CodemodApproved is true when a deterministic codemod has been vetted and
	// approved for Blanket AutoAccept at the codemod level (paper §2.7.2).
	CodemodApproved bool `json:"codemod_approved,omitempty"`

	// Changes are the semantic units composing the diff.
	Changes []Change `json:"changes,omitempty"`

	// --- scope / safety metadata (paper §2.7.3, §2.8 static heuristics) ---

	// OpenSource is true when the diff touches open-source code (excluded).
	OpenSource bool `json:"open_source,omitempty"`
	// SOXScoped is true when the diff touches SOX-scoped code (excluded).
	SOXScoped bool `json:"sox_scoped,omitempty"`
	// RequiresAdditionalReviews is true when the diff requires additional
	// mandatory reviewers (excluded from automation).
	RequiresAdditionalReviews bool `json:"requires_additional_reviews,omitempty"`
	// CI is the continuous-integration signal state; must be CIPassing.
	CI CISignal `json:"ci"`
	// State is the diff lifecycle state; must be DiffPublished.
	State DiffState `json:"state"`

	// CreatedAt is when the diff was created; used together with a runbook's
	// risk-history lookback window. Optional.
	CreatedAt time.Time `json:"created_at,omitempty"`
}

// LinesChanged returns a rough size measure for the diff: the number of changes
// weighted by their content length. Used by the heuristic risk scorer.
func (d Diff) LinesChanged() int {
	total := 0
	for _, c := range d.Changes {
		// Count newlines plus one as a cheap line estimate.
		lines := 1
		for _, r := range c.Content {
			if r == '\n' {
				lines++
			}
		}
		total += lines
	}
	return total
}

// MaxComplexity returns the highest per-change complexity in the diff.
func (d Diff) MaxComplexity() int {
	max := 0
	for _, c := range d.Changes {
		if c.Complexity > max {
			max = c.Complexity
		}
	}
	return max
}
